VisioConference.Main/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VisioConference.Main.Service;
using VisioConference.Models;

namespace VisioConference.Main.Controllers
{
	public class LoginController : Controller
	{
		private readonly IUtilisateurService _utilisateurService;

		public LoginController(IUtilisateurService exempleService)
		{
            _utilisateurService = exempleService;
		}

		//Get : Login
		public IActionResult Index()
		{
			if (User.Identity.IsAuthenticated)
				return RedirectToAction("Index", "Home");

			return View();
		}

		//Get : Login/Connection
		public IActionResult Connection()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Connection([Bind("Email,MotDePasse,IsPersistent")] Utilisateur utilisateur)
		{
			ViewData["MauvaisMotDePasse"] = "";
			ViewData["CompteInnexistant"] = "";

			var user = await _utilisateurService.Login(utilisateur.Email, utilisateur.MotDePasse, utilisateur.IsPersistent);

			if (user is null)
				return View();

			var email = user.FindFirst(ClaimTypes.Email).Value;
			var name = user.FindFirst(ClaimTypes.Name).Value;

			if(email == "")
			{
			ViewData["CompteInnexistant"] = "Cette adresse mail n'est pas associé à un compte Utilisateur.";
				return View(utilisateur);
		}

			if(name == "")
		{
				ViewData["MauvaisMotDePasse"] = "Mot de passe erroné.";
				return View(utilisateur);
		}

			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, user, 
				new AuthenticationProperties { IsPersistent = Convert.ToBoolean(user.FindFirst(ClaimTypes.IsPersistent).Value) });

			return RedirectToAction("Index", "Home");
		}

		public async Task<IActionResult> Deconnection()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			return RedirectToAction("Index", "Home");
		}
	}
}

VisioConference.Main/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using VisioConference.DAO;
using VisioConference.Models;

namespace VisioConference.Main.Controllers
{
	public class SignUpController : Controller
	{
		private readonly IUtilisateurDAO _utilisateurDAO;

		public SignUpController(IUtilisateurDAO utilisateurDAO)
		{
			_utilisateurDAO = utilisateurDAO;
		}

		//Get : SignUp
		public IActionResult Index()
		{
			return View();
		}

		//Get : SignUp/CreateAccount
		public IActionResult CreateAccount()
		{
			return View();
		}

		//Post : SignUp/CreateAccount
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateAccount([Bind("Id,Nom,Prenom,MotDePasse,DateDeNaissance,Email")] Utilisateur utilisateur)
		{
			await _utilisateurDAO.AddUtilisateur(utilisateur);
			return RedirectToAction("Index", "Home");
		}
	}
}

VisioConference.Main/Controllers/UtilisateursController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VisioConference.DAO;
using VisioConference.Models;

namespace VisioConference.Main.Controllers
{
    public class UtilisateursController : Controller
    {
        private readonly IUtilisateurDAO _utilisateurDAO;

        public UtilisateursController(IUtilisateurDAO utilisateurDAO)
        {
            _utilisateurDAO = utilisateurDAO;
        }

        // GET: Utilisateurs
        public async Task<IActionResult> Index()
        {
            return View(await _utilisateurDAO.GetAllUtilisateur());
        }

        //GET : Utilisateurs/SignUp
        public IActionResult SignUp()
        {
            return View();
        }

        //POST: Utilisateurs/SignUp
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([Bind("Id,Nom,Prenom,MotDePasse,DateDeNaissance,Email")] Utilisateur utilisateur)
        {            
            await _utilisateurDAO.AddUtilisateur(utilisateur);
            return RedirectToAction(nameof(Index));
        }

        // GET: Utilisateurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _utilisateurDAO == null)
                return NotFound();

            var utilisateur = await _utilisateurDAO.GetUtilisateurById((int)id);
            if (utilisateur == null)
                return NotFound();

            return View(utilisateur);
        }

        // GET: Utilisateurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _utilisateurDAO == null)
                return NotFound();

            var utilisateur = await _utilisateurDAO.GetUtilisateurById((int)id);
            if (utilisateur == null)
                return NotFound();

            return View(utilisateur);
        }

        // POST: Utilisateurs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prenom,MotDePasse,DateDeNaissance,Email")] Utilisateur utilisateur)
        {
            if (id != utilisateur.Id)
            {
                return NotFound();
            }

            try
            {
                await _utilisateurDAO.UpdateUtilisateur(utilisateur);
            }
            catch (DbUpdateConcurrencyException)
            {
                var u = await _utilisateurDAO.GetAllUtilisateur();
                if (!u.Contains(utilisateur))
                    return NotFound();
                else
                    throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Utilisateurs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _utilisateurDAO == null)
            {
                return NotFound();
            }

            var utilisateur = await _utilisateurDAO.GetUtilisateurById((int)id);
            if(utilisateur == null)
            {
                return NotFound();
            }
            return View(utilisateur);
        }

        // POST: Utilisateurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if(_utilisateurDAO == null)
            {
                return Problem("Entity set 'UtilisateurDAO' is null.");
            }

            var utilisateur = await _utilisateurDAO.GetUtilisateurById(id);
            if(utilisateur != null)
            {
                await _utilisateurDAO.DeleteUtilisateur(utilisateur);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

VisioConference.Main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Visio Conference</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VisioConference.Main.styles.css" asp-append-version="true" />
    <link href="//fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Visio Conference</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Utilisateurs" asp-action="Index">Utilisateurs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Connection">@ViewData["connection"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignUp" asp-action="CreateAccount">@ViewData["creation"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Deconnection">@ViewData["deconnection"]</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Visio Conference - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>